version: '3'
services:
  peanut:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    command: air
    volumes:
      - .:/peanut
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
