CREATE TABLE IF NOT EXISTS books (
	id BIGSERIAL NOT NULL,
	title TEXT NULL,
	description TEXT NULL,
	created_at TIMESTAMPTZ NULL,
	updated_at TIMESTAMPTZ NULL,
	deleted_at TIMESTAMPTZ NULL,
	CONSTRAINT books_pkey PRIMARY KEY (id)
);
