name: Verify code
run-name: Check ${{ github.actor }}'s commit
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      PROJECT_ID: peanut
      PEANUT_ENV: test
      PEANUT_LOCALE: en
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PEANUT_ENV: test
          envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          envkey_JWT_TTL: ${{ vars.JWT_TTL }}
      - name: Download dependencies
        run: go get .
      - name: Run unit test
        run: go test ./... -v -cover
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.0.9
        with:
          go-version: 1.19
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true
